### PR TITLE
Fixes #66 - sudachitra not being compatible with transformers version newer than 4.34

### LINKED ISSUE #66: sudachitra and other custom tokenizers no longer compatible with transformers later than 4.34
# System Info
transformers version: 4.34.0
Platform: linux
Python version: 3.9.18
sudachitra version: 0.1.8
sudachipy version: 0.6.7
sudachi-core version:20230927

Upstream changes in transformers due to PR: https://github.com/huggingface/transformers/pull/23909 causes error when
running the example over at: https://huggingface.co/megagonlabs/transformers-ud-japanese-electra-base-discriminator
this happens for other custom tokenizers as well: https://github.com/huggingface/transformers/issues/26777

```python3
from sudachitra import ElectraSudachipyTokenizer
tokenizer = ElectraSudachipyTokenizer.from_pretrained("megagonlabs/transformers-ud-japanese-electra-base-discriminator")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lib64/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2045, in from_pretrained
    return cls._from_pretrained(
  File "/home/lib64/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2256, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/lib64/python3.9/site-packages/sudachitra/tokenization_bert_sudachipy.py", line 155, in __init__
    super().__init__(
  File "/home/lib64/python3.9/site-packages/transformers/tokenization_utils.py", line 366, in __init__
    self._add_tokens(self.all_special_tokens_extended, special_tokens=True)
  File "/home/lib64/python3.9/site-packages/transformers/tokenization_utils.py", line 462, in _add_tokens
    current_vocab = self.get_vocab().copy()
  File "/home/lib64/python3.9/site-packages/sudachitra/tokenization_bert_sudachipy.py", line 218, in get_vocab
    return dict(self.vocab, **self.added_tokens_encoder)
AttributeError: 'ElectraSudachipyTokenizer' object has no attribute 'vocab'
```

If it is ok - I would like to contribute and submit a PR to fix for this issue.

### PR DESCRIPTION
**Pull request by mingboiz**
## Changes:
Mostly put the call to super.init() at the end of the init
As a result of the super.init() being set at the end after the sub_word_tokenize, the unk_token attribute was not set.
Had changed subword_tokenize behaviour referencing the same change being done in tokenization_bert_japanese as part of change [here](https://github.com/huggingface/transformers/pull/23909/files#diff-1a1e2482dde6b554d418cf503d1a04d4de8d0caf01fcfea12e085042972f45cbL231))
```diff
- self.subword_tokenizer = CharacterTokenizer(vocab=self.vocab, unk_token=self.unk_token)
+ self.subword_tokenizer = CharacterTokenizer(vocab=self.vocab, unk_token=str(unk_token))
```

### CODE REVIEW

**Comment by eiennohito** [comment]
Please change the last line of `requirements.txt` to `sudachidict_core==20210802.*`

Otherwise LGTM, will merge after the fix.

**Comment by eiennohito** [comment]
@katsutan any other comments?

**Comment by katsutan** [comment]
I think there is no problem.
The test will pass if you have the correct dictionary version.

**Comment by eiennohito** [comment]
Thank you very much for fix. @t-yamamura @katsutan probably we need to do a PyPI release.

**Comment by t-yamamura** [comment]
@mingboiz 
We released SudachiTra `v0.1.9` with this fix.
https://github.com/WorksApplications/SudachiTra/releases/tag/v0.1.9
https://pypi.org/project/SudachiTra/0.1.9/

Thanks for your support!

**Pull request merged**
